# Generated by Django 3.0.8 on 2020-10-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='created_by',
        ),
    ]
