# Generated by Django 3.0.8 on 2020-10-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0004_remove_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='price_unit',
            field=models.CharField(choices=[('Dollar', 'Dollar'), ('INR', 'INR')], default='INR', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CMSApp.Tier'),
        ),
    ]
