# Generated by Django 3.0 on 2020-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0005_auto_20201029_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='text_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
