# Generated by Django 3.0 on 2020-11-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0007_monthlybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
