# Generated by Django 3.0 on 2020-11-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0008_monthlybill_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybill',
            old_name='date',
            new_name='created_on',
        ),
    ]
