# Generated by Django 3.1.3 on 2020-11-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0010_auto_20201103_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
    ]
